# Generated by Django 3.0.3 on 2020-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_allforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelallformtypes',
            name='a_char_field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelallformtypes',
            name='a_date_time_field',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
