# Generated by Django 3.0.3 on 2020-02-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_allforms', '0002_auto_20200215_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelallformtypes',
            old_name='a_char_field',
            new_name='your_name',
        ),
    ]
